#!/bin/bash
set multiplot
name="Copper"
set xlabel "Distance (angstrom)" font "Times-Roman,14"
set ylabel "Energy (meV)" font "Times-Roman,16"
set title "Copper with Starting magnetization - Horizontal H2 distance" font "Times-Roman,14"
unset grid
unset key
set yrange [-60:200]
set ytics -60,15,200
set xrange [2.0:5]
set xtics 2.0,0.2,5

plot "top-cobre.dat" smooth cspline lc 1 title "top", "" with point pt 7 lc 1 notitle, "bridge-cobre.dat" smooth cspline lc 2 title  "bridge", "" with point pt 7 lc 2 notitle,"bridge2-cobre.dat" smooth cspline lc 3 title "bridge 2", "" with point pt 7 lc 3 notitle,"sixhollow-cobre.dat" smooth cspline lc 4 title "sixhollow", "" with point pt 7 lc 4 notitle,"baricentro-cobre.dat" smooth cspline lc 5 title "barycenter", "" with point pt 7 lc 5 notitle
clear
unset grid
set key right top
set key font "Times-Roman,8"
set key spacing 0.7
set size 0.5,0.5
set origin 0.45,0.45
set xrange [2.5:3.5]
set yrange [-45:35]
set xlabel ""
set ylabel ""
set title "Zoom" font "Times-Roman,8"

plot "top-cobre.dat" smooth cspline lc 1 title "top", "" with point pt 7 lc 1 notitle, "bridge-cobre.dat" smooth cspline lc 2 title  "bridge", "" with point pt 7 lc 2 notitle,"bridge2-cobre.dat" smooth cspline lc 3 title "bridge 2", "" with point pt 7 lc 3 notitle,"sixhollow-cobre.dat" smooth cspline lc 4 title "sixhollow", "" with point pt 7 lc 4 notitle,"baricentro-cobre.dat" smooth cspline lc 5 title "barycenter", "" with point pt 7 lc 5 notitle
unset multiplot   
