#!/bin/bash
name="Copper"
set xlabel "Distance (angstrom)" font "Times-Roman,14"
set ylabel "Energy (meV)" font "Times-Roman,16"
set title "Vanadium- Top horizontal H2 distance - Comparation" font "Times-Roman,14"
unset grid

plot "top-vanadio.dat" smooth cspline lc 1 title "no starting magnetization", "" with point pt 7 lc 1 notitle, "top-vanadio-magne.dat" smooth cspline lc 2 title  "with starting magnetization", "" with point pt 7 lc 2 notitle
